import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import Navbar from './components/Layout/Navbar/Navbar';
import TopBar from './components/Layout/TopBar/TopBar';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <div className='flex'>
          <Navbar />
          <div className='flex flex-col grow'>
            <TopBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
